@startuml Biodom

package layer0 <<Rectangle>> {
    interface IAnimal {
        void eat();
    }
}

package layer1 <<Rectangle>> {
    interface IMammal {
        void warmBlood();
    }
    interface IBird {
        void fly();
    }
    interface IReptile {
        void coldBlood();
    }
}

package layer2 <<Rectangle>> {
    interface IDog {
        void bark();
    }
    interface ICat {
        void meow();
    }
}

interface IBirth {
    void performBirth()
}

class LayEgg

class GiveLiveBirth

package ConcreteClass <<Rectangle>>{
    class Eagle
    class Owl
    class Crocodile
    class Snake
    class Chihuahua
    class Husky
    class MainCoon
    class LongHair
    class Platypus #GreenYellow
}

IMammal -- IAnimal
IBird -- IAnimal
IReptile -- IAnimal

Eagle -- IBird
Owl -- IBird

Crocodile -- IReptile
Snake -- IReptile

IDog -- IMammal
ICat -- IMammal

Chihuahua -- IDog
Husky -- IDog

MainCoon -- ICat
LongHair -- ICat

IBirth -- LayEgg
IBirth -- GiveLiveBirth

Platypus -- IMammal
Platypus -- IBirth

hide empty members

@enduml